// Run with: npm run db:migrate
// Applies pending Drizzle migrations generated by `npm run db:generate`.
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { migrate } from "drizzle-orm/postgres-js/migrator";

async function main() {
  if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not set");
  const isLocalDatabase = /localhost|127\.0\.0\.1/.test(process.env.DATABASE_URL);
  const client = postgres(process.env.DATABASE_URL, {
    ssl: isLocalDatabase ? false : "require",
    max: 1,
  });
  const db = drizzle(client);
  await migrate(db, { migrationsFolder: "./lib/db/migrations" });
  console.log("Migrations applied.");
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
