import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { blueprints } from "@/lib/db/schema";
import type { BlueprintOutput } from "@/lib/ai/schema";
import BlueprintView from "@/components/blueprint/BlueprintView";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";

export const runtime = "nodejs";
export const revalidate = 3600;
interface PageProps { params: Promise<{ shareToken: string }>; }
async function getBlueprint(shareToken: string) { const [blueprint] = await db.select().from(blueprints).where(eq(blueprints.shareToken, shareToken)).limit(1); if (!blueprint || !blueprint.isPublic) return null; return blueprint; }
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { shareToken } = await params; const blueprint = await getBlueprint(shareToken); if (!blueprint) return { title: "Blueprint not found — StackPilot", robots: { index: false, follow: true } };
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://stackpilot.by-rtc.com"; const url=`${baseUrl}/blueprint/${shareToken}`; const ogImage=`${baseUrl}/api/og?token=${shareToken}`; const description=`A StackPilot blueprint for ${blueprint.projectName}: tailored tech stack, AI model setup, cost estimates, and architecture notes.`;
  return { title:`${blueprint.projectName} — StackPilot Blueprint`,description,alternates:{canonical:url},robots:{index:true,follow:true},openGraph:{title:`${blueprint.projectName} — StackPilot Blueprint`,description,url,siteName:"StackPilot",images:[{url:ogImage,width:1200,height:630}],type:"article"},twitter:{card:"summary_large_image",title:`${blueprint.projectName} — StackPilot Blueprint`,description,images:[ogImage]}};
}
export default async function BlueprintPage({ params }: PageProps) {
  const { shareToken } = await params; const blueprint=await getBlueprint(shareToken); if(!blueprint) notFound();
  const recommendations=blueprint.recommendations as {lean:BlueprintOutput["lean"];balanced:BlueprintOutput["balanced"];scaleReady:BlueprintOutput["scaleReady"];architectureNotes:string};
  const aiSetup=(blueprint.aiSetup as BlueprintOutput["aiSetup"])??[]; const baseUrl=process.env.NEXT_PUBLIC_APP_URL??"https://stackpilot.by-rtc.com";
  const jsonLd={"@context":"https://schema.org","@type":"TechArticle",headline:`${blueprint.projectName} — Recommended Technology Stack`,description:`Recommended technology stack for ${blueprint.projectName}, generated by StackPilot.`,url:`${baseUrl}/blueprint/${blueprint.shareToken}`,datePublished:blueprint.createdAt.toISOString(),author:{"@type":"Organization",name:"StackPilot",url:baseUrl},publisher:{"@type":"Organization",name:"StackPilot",url:baseUrl},about:{"@type":"Thing",name:"Software architecture and technology stack"}};
  return <><SiteHeader/><main className="max-w-5xl mx-auto px-5 sm:px-8 py-12"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><BlueprintView blueprint={blueprint} recommendations={recommendations} aiSetup={aiSetup} architectureNotes={recommendations.architectureNotes}/></main><SiteFooter/></>;
}
