import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { db } from "@/lib/db";
import { blueprints } from "@/lib/db/schema";
import type { BlueprintOutput } from "@/lib/ai/schema";
import BlueprintView from "@/components/blueprint/BlueprintView";

export const runtime = "nodejs";
export const revalidate = 3600; // public blueprints are immutable-ish; revalidate hourly

interface PageProps {
  params: Promise<{ shareToken: string }>;
}

async function getBlueprint(shareToken: string) {
  const [blueprint] = await db
    .select()
    .from(blueprints)
    .where(eq(blueprints.shareToken, shareToken))
    .limit(1);
  if (!blueprint || !blueprint.isPublic) return null;
  return blueprint;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { shareToken } = await params;
  const blueprint = await getBlueprint(shareToken);
  if (!blueprint) return { title: "Blueprint not found — StackPilot" };

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://stackpilot.app";
  const url = `${baseUrl}/blueprint/${shareToken}`;
  const ogImage = `${baseUrl}/api/og?token=${shareToken}`;
  const description = `A StackPilot blueprint for ${blueprint.projectName}: tailored tech stack, AI model setup, cost estimates, and a launch roadmap.`;

  return {
    title: `${blueprint.projectName} — StackPilot Blueprint`,
    description,
    alternates: { canonical: url },
    openGraph: {
      title: `${blueprint.projectName} — StackPilot Blueprint`,
      description,
      url,
      siteName: "StackPilot",
      images: [{ url: ogImage, width: 1200, height: 630 }],
      type: "article",
    },
    twitter: {
      card: "summary_large_image",
      title: `${blueprint.projectName} — StackPilot Blueprint`,
      description,
      images: [ogImage],
    },
  };
}

export default async function BlueprintPage({ params }: PageProps) {
  const { shareToken } = await params;
  const blueprint = await getBlueprint(shareToken);
  if (!blueprint) notFound();

  const recommendations = blueprint.recommendations as {
    lean: BlueprintOutput["lean"];
    balanced: BlueprintOutput["balanced"];
    scaleReady: BlueprintOutput["scaleReady"];
    architectureNotes: string;
  };
  const aiSetup = (blueprint.aiSetup as BlueprintOutput["aiSetup"]) ?? [];

  const baseUrl = process.env.NEXT_PUBLIC_APP_URL ?? "https://stackpilot.app";

  // Schema.org structured data so search crawlers understand this page
  // describes a software architecture/tech-stack recommendation, improving
  // eligibility for rich results on stack-comparison searches.
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "SoftwareSourceCode",
    name: blueprint.projectName,
    description: `Recommended technology stack for ${blueprint.projectName}, generated by StackPilot.`,
    url: `${baseUrl}/blueprint/${blueprint.shareToken}`,
    dateCreated: blueprint.createdAt,
    programmingLanguage: [
      recommendations.balanced.frontend,
      recommendations.balanced.backend,
    ],
    codeRepository: undefined,
    author: { "@type": "Organization", name: "StackPilot", url: baseUrl },
  };

  return (
    <main className="max-w-5xl mx-auto px-5 sm:px-8 py-12">
      {/* eslint-disable-next-line react/no-danger */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <article>
        <BlueprintView
          blueprint={blueprint}
          recommendations={recommendations}
          aiSetup={aiSetup}
          architectureNotes={recommendations.architectureNotes}
        />
      </article>
    </main>
  );
}
