import { notFound } from "next/navigation"; import Link from "next/link"; import SiteHeader from "@/components/SiteHeader"; import SiteFooter from "@/components/SiteFooter"; import ToolClient from "@/components/tools/ToolClient"; import AdSlot from "@/components/AdSlot";
const data:Record<string,{title:string;description:string;how:string}>={
"ai-api-cost-calculator":{title:"AI API Cost Calculator",description:"Estimate monthly AI API spending from input and output token usage.",how:"Enter the number of input and output tokens you expect to use in a month and the provider's current price per million tokens. The estimate multiplies usage by the relevant unit price."},
"startup-cost-calculator":{title:"Startup Cost Calculator",description:"Estimate recurring monthly and annual infrastructure costs for a startup.",how:"Add your expected hosting, database, AI, storage, email and other service costs. The calculator totals recurring infrastructure expenses."},
"saas-mrr-calculator":{title:"SaaS MRR Calculator",description:"Calculate monthly recurring revenue and annual recurring revenue from customers and average revenue.",how:"Multiply paying customers by average monthly revenue per customer. ARR is MRR multiplied by twelve."},
"saas-churn-calculator":{title:"SaaS Churn Calculator",description:"Calculate monthly customer churn and retention.",how:"Divide customers lost during the month by customers at the start of the month. The result is the simple monthly customer churn rate."},
"saas-ltv-calculator":{title:"SaaS LTV Calculator",description:"Estimate SaaS customer lifetime value from ARPU, margin and monthly churn.",how:"The simple model used here is ARPU multiplied by gross margin, divided by monthly churn expressed as a decimal. It is a planning estimate."},
"saas-cac-calculator":{title:"SaaS CAC Calculator",description:"Calculate customer acquisition cost from sales and marketing spend.",how:"Divide sales and marketing spend for a period by the number of new customers acquired in that period."},
"stripe-fee-calculator":{title:"Stripe Fee Calculator",description:"Estimate transaction fees and net revenue using your own fee assumptions.",how:"Enter the percentage fee and fixed fee that apply to your account, then multiply the resulting fee by your transaction count."},
"token-cost-calculator":{title:"Token Cost Calculator",description:"Estimate language-model API costs from input and output tokens.",how:"Multiply input tokens and output tokens by their respective provider prices per million tokens. Verify current pricing with the provider before making a budget."},
"bandwidth-calculator":{title:"Bandwidth Calculator",description:"Estimate monthly bandwidth from visitors, pages per visitor and average page size.",how:"Monthly visitors multiplied by pages per visitor multiplied by average page size gives approximate monthly data transfer."},
"tech-stack-generator":{title:"Tech Stack Generator",description:"Generate a practical starting technology stack for your product.",how:"Select your product type and team size. StackPilot provides a simple starting architecture; treat it as a planning recommendation and validate it against your actual requirements."}};
export function generateStaticParams(){return Object.keys(data).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=data[slug];return d?{title:d.title,description:d.description}:{title:"Tool"}}
export default async function ToolPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const d=data[slug];if(!d)notFound();return <><SiteHeader/><main className="max-w-4xl mx-auto px-5 sm:px-8 py-12"><div className="text-xs text-navy-soft"><Link href="/tools">Tools</Link> / {d.title}</div><h1 className="font-head text-4xl sm:text-5xl font-bold text-navy mt-4">{d.title}</h1><p className="mt-3 text-lg text-navy-soft">{d.description}</p><AdSlot/><ToolClient tool={slug as Parameters<typeof ToolClient>[0]["tool"]}/><section className="mt-10 bg-white border border-border rounded-2xl p-6 sm:p-8"><h2 className="font-head text-2xl font-bold text-navy">How it works</h2><p className="mt-3 leading-7 text-navy-soft">{d.how}</p><h2 className="font-head text-2xl font-bold text-navy mt-8">Important note</h2><p className="mt-3 leading-7 text-navy-soft">This calculator provides an estimate, not a quote. Provider pricing, taxes, regions, usage limits and account-specific terms can change the actual result.</p></section></main><SiteFooter/></> }